export const FETCH_CONTACTS_SUCCESS = "FETCH_CONTACTS_SUCCESS";
export const FETCH_CONTACTS_FAILURE = "FETCH_CONTACTS_FAILURE";


export const SET_MODAL = "SET_MODAL";
export const CHANGE_CONTACT_DATA = "CHANGE_CONTACT_DATA";
export const CLEAR_CONTACT_DATA = "CLEAR_CONTACT_DATA";

export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";

export const CONTACT_SUCCESS = "CONTACT_SUCCESS";
export const CONTACT_FAILURE = "CONTACT_FAILURE";

export const GET_ID = "GET_ID";
export const EDIT_CONTACT = "EDIT_CONTACT";

